version: "3.7"

services:
  kamodo-py36:
    image: ensemble/kamodo-py36
    ports:
      - "8888:8888"
    build: 
      context: .
      dockerfile: dockerfiles/kamodo-py36.Dockerfile
    command:
      - jupyter
      - notebook
      - /kamodo
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
  kamodo-py37:
    image: ensemble/kamodo-py37
    ports:
      - "8888:8888"
    build: 
      context: .
      dockerfile: dockerfiles/kamodo-py37.Dockerfile
    command:
      - jupyter
      - notebook
      - /kamodo
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
  kamodo-dev-py37:
    image: ensemble/kamodo-py37
    ports:
      - "8889:8888"
    build: 
      context: .
      dockerfile: dockerfiles/kamodo-py37.Dockerfile
    command:
      - jupyter
      - notebook
      - /kamodo
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
    volumes:
      - type: bind
        source: ${PWD}
        target: /kamodo
    working_dir: /kamodo
  kamodo-test-py36:
    image: ensemble/kamodo-test-py36
    build: 
      context: .
      dockerfile: dockerfiles/kamodo-test-py36.Dockerfile
    volumes:
      - type: bind
        source: ${PWD}
        target: /kamodo
    working_dir: /kamodo
    command: ["sh", "-c", "chmod +x /kamodo/test_kamodo.sh && /kamodo/test_kamodo.sh"]
  kamodo-test-py37:
    image: ensemble/kamodo-test-py37
    build: 
      context: .
      dockerfile: dockerfiles/kamodo-test-py37.Dockerfile
    volumes:
      - type: bind
        source: ${PWD}
        target: /kamodo
    working_dir: /kamodo
    command: ["sh", "-c", "chmod +x /kamodo/test_kamodo.sh && /kamodo/test_kamodo.sh"]

