version: "3.7"

services:
  kamodo:
    image: ensemble/kamodo
    ports:
      - "8888:8888"
    build: 
      context: .
      dockerfile: dockerfiles/kamodo.Dockerfile
    command:
      - jupyter
      - notebook
      - /kamodo
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
  kamodo-dev:
    image: ensemble/kamodo
    ports:
      - "8889:8888"
    build: 
      context: .
      dockerfile: dockerfiles/kamodo.Dockerfile
    command:
      - jupyter
      - notebook
      - /kamodo
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
    volumes:
      - type: bind
        source: ${PWD}
        target: /kamodo
    working_dir: /kamodo
  kamodo-test:
    image: ensemble/kamodo-test
    build: 
      context: .
      dockerfile: dockerfiles/kamodo-test.Dockerfile
    volumes:
      - type: bind
        source: ${PWD}
        target: /kamodo
    working_dir: /kamodo
    command:
      - pytest
      - --cov
      - kamodo.kamodo
      - --cov
      - kamodo.util
      - --cov
      - plotting
      - kamodo/test_plotting.py
      - kamodo/test_kamodo.py
      - kamodo/test_utils.py
      - jupyter nbconvert
      - --to=html
      - --ExecutePreprocessor.enabled=True
      - --config docs/notebooks/run_notebooks.py



