version: "3.7"

services:
  kamodo:
    image: ensemble/kamodo
    ports:
      - "8888:8888"
    build: 
      context: .
      dockerfile: dockerfiles/kamodo.Dockerfile
    command:
      - jupyter
      - notebook
      - /kamodo
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
  kamodo-dev:
    image: ensemble/kamodo
    ports:
      - "8889:8888"
    build: 
      context: .
      dockerfile: dockerfiles/kamodo.Dockerfile
    command:
      - jupyter
      - notebook
      - /kamodo
      - --port=8888
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
    volumes:
      - type: bind
        source: ${PWD}
        target: /kamodo
    working_dir: /kamodo